import Calculator from "@/components/calculator";
import Navbar from "@/components/navbar";
import Head from "next/head";
import styles from "../styles/home.module.css";
import { InfoBlock } from "@/components/info-block";
export default function Home() {
  return (
    <>
      <Head>
        <title>
          Calculadora de FGTS: confira o valor disponivel para saque
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1 user-scalable=no"
        />
        <link rel="icon" href="/calculando.png" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>
            CALCULE SEU FGTS! CONFIRA O VALOR DISPONIVEL PARA SAQUE
          </h1>
          <p className={styles.subtitle}>
            Com essa calculadora você pode conferir o valor exato que você tem
            no seu Fundo de Garantia do Tempo de Serviço.
          </p>
          <Calculator />
          <InfoBlock
            title="O que é FGTS?"
            info="FGTS é a sigla para Fundo de Garantia do Tempo de Serviço. É um
              fundo criado pelo Governo Federal do Brasil em 1966 com o objetivo
              de proteger o trabalhador em casos de demissão sem justa causa,
              além de servir como uma forma de poupança forçada para o
              trabalhador. Todo trabalhador com carteira assinada é obrigado a
              ter uma conta de FGTS."
          />

          <InfoBlock
            title="Como ter direito ao FGTS?"
            info="Para ter direito ao FGTS, o trabalhador precisa estar registrado
              em carteira de trabalho, seja em contrato de trabalho por tempo
              determinado ou indeterminado. O empregador é obrigado a depositar
              mensalmente o valor correspondente a 8% do salário bruto do
              trabalhador em uma conta individual em nome do trabalhador na
              Caixa Econômica Federal."
          />

          <InfoBlock
            title="Como funciona o saque do FGTS?"
            info="O saque do FGTS pode ser feito em situações específicas, tais
              como:"
            extraInfo=" Para solicitar o saque do FGTS, o trabalhador deve comparecer a
            uma agência da Caixa Econômica Federal com a documentação
            necessária para comprovar a situação que dá direito ao saque. Em
            alguns casos, o saque pode ser feito por meio eletrônico, por meio
            do aplicativo FGTS ou do site da Caixa."
            list={[
              {
                head: "Demissão sem justa causa",
                text: "o trabalhador tem direito a sacar o valor total do FGTS depositado em sua conta, além de uma multa de 40% sobre esse valor, paga pelo empregador.",
              },
              {
                head: "Aposentadoria",
                text: "o trabalhador pode sacar o valor total do FGTS depositado em sua conta.",
              },
              {
                head: "Compra da casa própria",
                text: "o trabalhador pode usar o valor do FGTS para financiar a compra de um imóvel.",
              },
              {
                head: "Doenças graves",
                text: "o trabalhador ou seu dependente podem sacar o FGTS para tratamento de doenças graves, tais como câncer, AIDS, dentre outras.",
              },
              {
                head: "Situações de calamidade pública",
                text: "em casos de desastres naturais ou outras situações de calamidade pública, o trabalhador pode sacar o FGTS.",
              },
            ]}
          />
        </div>
      </main>
    </>
  );
}
