import Calculator from "@/components/calculator";
import Navbar from "@/components/navbar";
import Head from "next/head";
import styles from "../styles/home.module.css";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1 user-scalable=no"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.container}>
          <Calculator />
          {/* anuncio aqui */}
          <div>
            <h1>FGTS: o que é?</h1>
          </div>
        </div>
      </main>
    </>
  );
}
